### ISSUE TITLE
Добавить распознавание QR-кода

### ISSUE THREAD

**Issue by kolyanok** [QTJournal/QTJournal#10]
Добавить библиотеку (думаю, стоит использовать эту https://github.com/ftylitak/qzxing/) для распознавания QR-кодов и реализовать с ее помощью, собственно, само распознавание кода из файла, затем проверить работу всего этого на QR-коде с TJ.

**Comment by kolyanok** [comment]
Вроде бы можно закрывать?

**Comment by fullFeaturedUnicorn** [comment]
Лол ты ещё не?

**Comment by kolyanok** [comment]
Ладно
