### ISSUE TITLE
Продолжение работы над проектом

### ISSUE THREAD

**Issue by kolyanok** [QTJournal/QTJournal#15]
Добрый вечер, товарищи.
В связи с тем, что обновление все же выкатили, а проект мы, вроде как, отложили именно до этого момента, возник резонный вопрос: что будем делать дальше?
В новом апи все переделали и теперь нам тоже придется все переделать.
Я уже понаблюдал за работой приложения с новым апи и могу сказать, что в нем все стало куда попроще. Соответственно, на реализацию работы с ним уйдет куда меньше времени.
 @fullFeaturedUnicorn @romangr , что вы думаете? Будем продолжать работу над этой штукой?

**Comment by romangr** [comment]
Привет. Что-то давно не проверял письма в папке от гитхаба. Я бы продолжил, на самом деле, потому что вроде с тж не собираюсь уходить, а в этой штуке можно будет сделать все, как будет удобно нам и не ждать, пока кто-то выкатит изменения на сайт.
@kolyanok

**Comment by kolyanok** [comment]
Привет. Я бы тоже, в принципе, продолжил работу. Единственное - там вообще все поменяли. Можешь пока для начала починить парсер для страницы новостей? Сам запрос я уже сделал https://github.com/QTJournal/QTJournal/commit/88a7cc87c3c90112c5ddab20d1de3517d15b4e08
Спасибо. 
Kat Vance мне в твиторе написал, что он не хочет
Но, думаю, мы вдвоем, в принципе, справимся. Сейчас главная проблема - я совсем не понимаю, как в Qt сделать человеческий интерфейс... В остальном вроде все понятно: раздобыть где-то/написать самим доку к новому апи, все переделать, допилить наконец просмотр статьи и будет уже первая рид-онли альфа...
С апи я буду копаться сам, думаю. Уже написал https://github.com/cmtt-ru/api/issues/8#issuecomment-317327983 , но Чекальский упорно ингорирует ее :(

**Comment by romangr** [comment]
Про интерфейс я тоже не знаю ничего, придется с нуля разбираться, видимо. Пока можно выкатить в дефолтном интерфейсе, как у нас сейчас прога, просто сделать функционал, может кто еще заинтересуется и поможет потом.
Парсер починю, если не сегодня/завтра, то на выходных, пока не знаю, сколько дел на работе будет
https://github.com/QTJournal/QTJournal/issues/16

**Comment by fullFeaturedUnicorn** [comment]
Ладно, хуй с вами, я тоже где-то на горизонте (наверное) маячить буду. Интерфейс я рисовал, если колянок вспомнит, куда я его положил, будет заготовка, от которой можно отталкиваться.
Практика в плюсах никогда лишней не будет, можете грузить на меня несложные и не критичные, либо связанные с UI/UX issues.
Моё отношение к проджекту сейчас – образовательно-тренировочное. На сам тж как явление скорее насрать, чем не насрать.
UPD: Оставлю единственный на сегодняшний момент способ (кроме почты) меня быстро найти: [тык](https://matrix.to/#/@noperope:matrix.org)

**Comment by DenisSergeevitch** [comment]
Привет, вообще мы обсуждаем публичное API — но если есть желание, можем помочь с закрытым, но чуть позже. 

Сотрудник TJ

**Comment by kolyanok** [comment]
@DenisSergeevitch а дока к открытым методам хотя бы будут опубликована? Если да, то когда? Просто я могу как и с предыдущей версией (https://github.com/QTJournal/api) путем реверс-инжинеринга приложений iOS/Android создать новую версию документации, но не хочу делать бесполезную работу, если вы потом все опубликуете :)

**Comment by romangr** [comment]
Ну по UI можно пока попробовать хотя бы один нарисованный экран реализовать, чтобы понимать, как потом с этим иметь дело.
Поставил себе riot, можно [там](https://matrix.to/#/#qtjournal:matrix.org) обсуждать теперь, наверное, если всем удобно

**Comment by DenisSergeevitch** [comment]
@kolyanok я просто боюсь API в данный момент не финальное, поэтому я бы взял паузу и действительно поработал пока над UI, я думаю через пару недель мы более-менее решим какое у нас будет API.

**Comment by kolyanok** [comment]
Ну ладно

**Comment by kolyanok** [comment]
@DenisSergeevitch , Денис, слушай, а как с тобой можно связаться? Дай, пожалуйста, телегу или что-нибудь еще. Просто есть вопросы кое-какие по технической части TJ. Очень хотелось бы поговорить немного...

**Comment by kokoulin** [comment]
а че нить известно с публичной частью апи?

**Comment by kolyanok** [comment]
Ну и как там? Что с апи?

**Comment by DenisSergeevitch** [comment]
Только закончили с внутренней документацией, подумаем насколько шарибельно — вернусь чуть позже

**Comment by kolyanok** [comment]
Ну ладно :/

**Comment by DmitryZemlyuk** [comment]
Всем привет.
Чем все закончилось? :)

**Comment by kolyanok** [comment]
Пока, вроде, ничем ¯\\_(ツ)\_/¯

**Comment by DenisSergeevitch** [comment]
PR вычитываем по идее, закончим скоро

**Comment by kolyanok** [comment]
Ну и чо?

**Comment by DenisSergeevitch** [comment]
Превет http://shir-man.com/static/tjapi/
