### ISSUE TITLE
Починить парсер для страницы новостей

### ISSUE THREAD

**Issue by romangr** [QTJournal/QTJournal#16]

**Comment by kolyanok** [comment]
@romangr, мой скачиватель страницы новостей остался рабочим до сих пор, поэтому, раз Денис выложил документацию API, жду парсер от тебя :) Почини, пожалуйста, как будет время.

**Comment by romangr** [comment]
Нужно попробовать использовать вот эту штуку
https://github.com/Loki-Astari/ThorsSerializer/blob/master/doc/example1.md

**Comment by kolyanok** [comment]
Можешь попробовать.
Я завтра прилечу домой и гляну, что там.
Может быть даже что-нибудь по интерфейсу попробую намутить...

**Comment by kolyanok** [comment]
Можно закрывать?

**Comment by romangr** [comment]
Ага
