### ISSUE TITLE
Реализация работы с API - Пользователь

### ISSUE THREAD

**Issue by romangr** [QTJournal/QTJournal#2]
- [x]     Информация о пользователе
- [x]     Записи пользователя
- [x]     Комментарии пользователя
- [x]     Уведомления
- [x]     Избранное
- [x]     Добавить в избранное
- [x]     Удалить из избранного
- [x]     Настройки аккаунта
- [x]     Изменить настройки аккаунта

**Comment by kolyanok** [comment]
https://github.com/QTJournal/QTJournal/commit/e4c0456bd60cf1c8baa5ac779a36dd75add11b30
