### ISSUE TITLE
Реализация работы с API - Прочее

### ISSUE THREAD

**Issue by romangr** [QTJournal/QTJournal#7]
- [x]  Отправка опечаток
- [x]     Определение статьи по URL

**Comment by kolyanok** [comment]
>Подписка на push-уведомления
>Отписка от push-уведомлений

А целесообразно ли? Это, вроде как, все равно работать может только на мобильных ОС.

**Comment by romangr** [comment]
>А целесообразно ли? Это, вроде как, все равно работать может только на мобильных ОС.

Да, наверное можно выпилить

**Comment by kolyanok** [comment]
Ну ок

**Comment by kolyanok** [comment]
https://github.com/QTJournal/QTJournal/commit/901c39f9415eda73b0e4735e7b8410c4ab0d2718
